# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  displayName: Prepare SonarCloud analysis
  inputs:
    SonarCloud: 'sonarcloud-tri'
    organization: 'tri-nguyen'
    scannerMode: 'MSBuild'
    projectKey: 'global-tri'
    extraProperties: |
        sonar exclusion=**/lib**

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: ./WatchStoreApp

- script: dotnet test
  displayName: dotnet test
  workingDirectory: WatchStoreApp
  
- task: SonarCloudAnalyze@1
  displayName: Rune SonarCloud analysis

- task: SonarCloudPublish@1
  displayName: Publish SonarCloud quality gate result

- task: DotNetCoreCLI@2
  displayName: dotnet publish + zip
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(b5839134-afc5-4925-bf69-3293aa8216e7)'
    appType: 'webApp'
    WebAppName: 'joemamapokemon'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'


